const data = [
  {
    department: "Research and Development",
    company: "Pixonyx",
    gender: "Male",
    language: "Bengali",
    first_name: "Clayborn",
    ssn: "892-47-5068",
  },
  {
    department: "Sales",
    company: "Yodo",
    gender: "Male",
    language: "Gujarati",
    first_name: "Tabb",
    ssn: "461-52-4058",
  },
  {
    department: "Product Management",
    company: "Lazz",
    gender: "Male",
    language: "English",
    first_name: "Herbie",
    ssn: "320-46-4214",
  },
  {
    department: "Support",
    company: "Gigaclub",
    gender: "Male",
    language: "Guaraní",
    first_name: "Taylor",
    ssn: "450-82-9019",
  },
  {
    department: "Human Resources",
    company: "Wordify",
    gender: "Female",
    language: "Croatian",
    first_name: "Rosette",
    ssn: "277-41-6117",
  },
  {
    department: "Business Development",
    company: "Voonder",
    gender: "Female",
    language: "Belarusian",
    first_name: "Aidan",
    ssn: "188-58-3860",
  },
  {
    department: "Engineering",
    company: "Twitterbeat",
    gender: "Genderfluid",
    language: "Chinese",
    first_name: "Juliette",
    ssn: "247-68-6514",
  },
  {
    department: "Accounting",
    company: "Edgeblab",
    gender: "Bigender",
    language: "Mongolian",
    first_name: "Geoffrey",
    ssn: "799-58-7286",
  },
  {
    department: "Engineering",
    company: "Flipbug",
    gender: "Female",
    language: "Estonian",
    first_name: "Rebeca",
    ssn: "570-53-6528",
  },
  {
    department: "Engineering",
    company: "Feedbug",
    gender: "Male",
    language: "Amharic",
    first_name: "Agosto",
    ssn: "177-73-5557",
  },
  {
    department: "Services",
    company: "Jamia",
    gender: "Male",
    language: "Swahili",
    first_name: "Maximilian",
    ssn: "573-51-7703",
  },
  {
    department: "Research and Development",
    company: "Jabbertype",
    gender: "Female",
    language: "Georgian",
    first_name: "Marys",
    ssn: "781-64-3651",
  },
  {
    department: "Research and Development",
    company: "Voolia",
    gender: "Female",
    language: "Azeri",
    first_name: "Blinnie",
    ssn: "146-69-2939",
  },
  {
    department: "Legal",
    company: "Thoughtstorm",
    gender: "Polygender",
    language: "Quechua",
    first_name: "Kelcey",
    ssn: "280-26-2111",
  },
  {
    department: "Business Development",
    company: "Jayo",
    gender: "Male",
    language: "Oriya",
    first_name: "Barnabas",
    ssn: "848-67-6613",
  },
  {
    department: "Sales",
    company: "Jatri",
    gender: "Polygender",
    language: "Swedish",
    first_name: "Germain",
    ssn: "478-95-4872",
  },
  {
    department: "Business Development",
    company: "Trupe",
    gender: "Bigender",
    language: "German",
    first_name: "Bennie",
    ssn: "559-89-7506",
  },
  {
    department: "Sales",
    company: "Shuffletag",
    gender: "Genderqueer",
    language: "Korean",
    first_name: "Bronson",
    ssn: "211-19-9174",
  },
  {
    department: "Accounting",
    company: "Jayo",
    gender: "Male",
    language: "Dhivehi",
    first_name: "Tedd",
    ssn: "318-58-5233",
  },
  {
    department: "Marketing",
    company: "Bluejam",
    gender: "Polygender",
    language: "Georgian",
    first_name: "Ofelia",
    ssn: "861-41-8096",
  },
  {
    department: "Engineering",
    company: "Zoonoodle",
    gender: "Female",
    language: "Pashto",
    first_name: "Emmalee",
    ssn: "343-76-4589",
  },
  {
    department: "Services",
    company: "Mydo",
    gender: "Female",
    language: "Amharic",
    first_name: "Arabella",
    ssn: "630-26-3988",
  },
  {
    department: "Engineering",
    company: "Edgewire",
    gender: "Non-binary",
    language: "Tamil",
    first_name: "Chevalier",
    ssn: "696-26-7849",
  },
  {
    department: "Marketing",
    company: "Gigabox",
    gender: "Male",
    language: "Bosnian",
    first_name: "Berky",
    ssn: "686-48-2099",
  },
  {
    department: "Sales",
    company: "Skimia",
    gender: "Non-binary",
    language: "Arabic",
    first_name: "Melitta",
    ssn: "610-72-4130",
  },
  {
    department: "Training",
    company: "Thoughtbridge",
    gender: "Male",
    language: "Maltese",
    first_name: "Ramsay",
    ssn: "319-53-9296",
  },
  {
    department: "Support",
    company: "Zoomlounge",
    gender: "Male",
    language: "Assamese",
    first_name: "Sigfrid",
    ssn: "451-29-6433",
  },
  {
    department: "Legal",
    company: "Demimbu",
    gender: "Female",
    language: "Swedish",
    first_name: "Loutitia",
    ssn: "813-55-8280",
  },
  {
    department: "Training",
    company: "Quimba",
    gender: "Male",
    language: "Khmer",
    first_name: "Whitaker",
    ssn: "872-42-8544",
  },
  {
    department: "Engineering",
    company: "Aimbo",
    gender: "Male",
    language: "Lithuanian",
    first_name: "Laughton",
    ssn: "174-22-1459",
  },
  {
    department: "Accounting",
    company: "Chatterbridge",
    gender: "Female",
    language: "Nepali",
    first_name: "Willetta",
    ssn: "884-32-4571",
  },
  {
    department: "Human Resources",
    company: "Shuffletag",
    gender: "Genderqueer",
    language: "Lao",
    first_name: "Jeffry",
    ssn: "665-69-1009",
  },
  {
    department: "Product Management",
    company: "Blogpad",
    gender: "Female",
    language: "Papiamento",
    first_name: "Perla",
    ssn: "676-57-6704",
  },
  {
    department: "Research and Development",
    company: "Nlounge",
    gender: "Female",
    language: "Kazakh",
    first_name: "Flo",
    ssn: "428-58-3413",
  },
  {
    department: "Services",
    company: "Devify",
    gender: "Female",
    language: "Montenegrin",
    first_name: "Delia",
    ssn: "560-30-2135",
  },
  {
    department: "Sales",
    company: "Vinder",
    gender: "Male",
    language: "Romanian",
    first_name: "Whitaker",
    ssn: "477-99-9552",
  },
  {
    department: "Support",
    company: "Buzzshare",
    gender: "Bigender",
    language: "Nepali",
    first_name: "Honor",
    ssn: "426-40-8037",
  },
  {
    department: "Sales",
    company: "Yombu",
    gender: "Female",
    language: "Macedonian",
    first_name: "Natividad",
    ssn: "379-18-6140",
  },
  {
    department: "Legal",
    company: "Chatterpoint",
    gender: "Female",
    language: "Fijian",
    first_name: "Terra",
    ssn: "144-51-8794",
  },
  {
    department: "Human Resources",
    company: "Chatterpoint",
    gender: "Male",
    language: "English",
    first_name: "Saundra",
    ssn: "755-78-3233",
  },
  {
    department: "Services",
    company: "Vimbo",
    gender: "Polygender",
    language: "Yiddish",
    first_name: "Uriel",
    ssn: "878-84-8470",
  },
  {
    department: "Human Resources",
    company: "Yambee",
    gender: "Female",
    language: "Polish",
    first_name: "De",
    ssn: "595-25-0206",
  },
  {
    department: "Human Resources",
    company: "Demimbu",
    gender: "Non-binary",
    language: "Azeri",
    first_name: "Tabor",
    ssn: "824-35-0413",
  },
  {
    department: "Marketing",
    company: "Twiyo",
    gender: "Female",
    language: "Croatian",
    first_name: "Lolita",
    ssn: "442-29-4898",
  },
  {
    department: "Legal",
    company: "Mita",
    gender: "Female",
    language: "Mongolian",
    first_name: "Hildagard",
    ssn: "866-27-0402",
  },
  {
    department: "Research and Development",
    company: "Fliptune",
    gender: "Male",
    language: "Albanian",
    first_name: "Arturo",
    ssn: "769-72-5809",
  },
  {
    department: "Product Management",
    company: "Chatterpoint",
    gender: "Male",
    language: "Chinese",
    first_name: "Booth",
    ssn: "627-62-6189",
  },
  {
    department: "Business Development",
    company: "Meevee",
    gender: "Female",
    language: "Irish Gaelic",
    first_name: "Hermia",
    ssn: "382-35-3086",
  },
  {
    department: "Product Management",
    company: "Photofeed",
    gender: "Male",
    language: "Swahili",
    first_name: "Stefano",
    ssn: "819-69-4017",
  },
  {
    department: "Accounting",
    company: "Centizu",
    gender: "Male",
    language: "Polish",
    first_name: "Giffy",
    ssn: "378-38-9426",
  },
  {
    department: "Sales",
    company: "Geba",
    gender: "Male",
    language: "Hindi",
    first_name: "Myles",
    ssn: "321-94-3735",
  },
  {
    department: "Legal",
    company: "Meevee",
    gender: "Female",
    language: "Dhivehi",
    first_name: "Julieta",
    ssn: "445-18-7263",
  },
  {
    department: "Legal",
    company: "Pixonyx",
    gender: "Male",
    language: "Gagauz",
    first_name: "Claire",
    ssn: "489-29-3752",
  },
  {
    department: "Training",
    company: "Oyondu",
    gender: "Female",
    language: "Polish",
    first_name: "Juline",
    ssn: "140-31-9034",
  },
  {
    department: "Human Resources",
    company: "Oba",
    gender: "Male",
    language: "Latvian",
    first_name: "Micheal",
    ssn: "148-74-3059",
  },
  {
    department: "Services",
    company: "Roombo",
    gender: "Female",
    language: "Aymara",
    first_name: "Ellissa",
    ssn: "771-24-8138",
  },
  {
    department: "Business Development",
    company: "Zoomzone",
    gender: "Female",
    language: "Aymara",
    first_name: "Edy",
    ssn: "857-98-1766",
  },
  {
    department: "Marketing",
    company: "Jabbertype",
    gender: "Female",
    language: "Tetum",
    first_name: "Doll",
    ssn: "871-98-6171",
  },
  {
    department: "Marketing",
    company: "Thoughtbeat",
    gender: "Male",
    language: "Bengali",
    first_name: "Antonin",
    ssn: "195-73-6219",
  },
  {
    department: "Research and Development",
    company: "Eadel",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Marcelline",
    ssn: "162-72-2679",
  },
  {
    department: "Human Resources",
    company: "Linklinks",
    gender: "Female",
    language: "Kyrgyz",
    first_name: "Amalee",
    ssn: "249-47-0702",
  },
  {
    department: "Training",
    company: "Pixonyx",
    gender: "Female",
    language: "Punjabi",
    first_name: "Susanne",
    ssn: "708-44-7536",
  },
  {
    department: "Support",
    company: "Roodel",
    gender: "Male",
    language: "Fijian",
    first_name: "Pablo",
    ssn: "875-64-0346",
  },
  {
    department: "Business Development",
    company: "Abata",
    gender: "Female",
    language: "Arabic",
    first_name: "Margarette",
    ssn: "333-55-7618",
  },
  {
    department: "Accounting",
    company: "Feedfish",
    gender: "Male",
    language: "Kyrgyz",
    first_name: "Dieter",
    ssn: "316-82-2186",
  },
  {
    department: "Services",
    company: "Skilith",
    gender: "Female",
    language: "Greek",
    first_name: "Jaymee",
    ssn: "424-01-8738",
  },
  {
    department: "Engineering",
    company: "Livetube",
    gender: "Female",
    language: "Dari",
    first_name: "Merrie",
    ssn: "815-48-9674",
  },
  {
    department: "Product Management",
    company: "Innojam",
    gender: "Female",
    language: "Bislama",
    first_name: "Emily",
    ssn: "625-36-6255",
  },
  {
    department: "Engineering",
    company: "Mudo",
    gender: "Male",
    language: "Kyrgyz",
    first_name: "Jeffie",
    ssn: "652-96-0517",
  },
  {
    department: "Business Development",
    company: "Rhyloo",
    gender: "Male",
    language: "Hiri Motu",
    first_name: "Teddie",
    ssn: "635-92-2623",
  },
  {
    department: "Legal",
    company: "Tazzy",
    gender: "Female",
    language: "Dari",
    first_name: "Shannah",
    ssn: "777-79-2162",
  },
  {
    department: "Legal",
    company: "Reallinks",
    gender: "Female",
    language: "Spanish",
    first_name: "Lauretta",
    ssn: "578-59-8265",
  },
  {
    department: "Support",
    company: "Katz",
    gender: "Female",
    language: "Burmese",
    first_name: "Biddy",
    ssn: "701-96-3737",
  },
  {
    department: "Product Management",
    company: "Trilith",
    gender: "Female",
    language: "Papiamento",
    first_name: "Carlee",
    ssn: "668-79-8394",
  },
  {
    department: "Marketing",
    company: "Rooxo",
    gender: "Female",
    language: "Lithuanian",
    first_name: "Natasha",
    ssn: "172-11-6036",
  },
  {
    department: "Training",
    company: "Skalith",
    gender: "Male",
    language: "Burmese",
    first_name: "Derrek",
    ssn: "431-57-3156",
  },
  {
    department: "Business Development",
    company: "Skaboo",
    gender: "Genderfluid",
    language: "Italian",
    first_name: "Quinn",
    ssn: "284-12-4131",
  },
  {
    department: "Human Resources",
    company: "BlogXS",
    gender: "Female",
    language: "Portuguese",
    first_name: "Sharia",
    ssn: "504-61-5832",
  },
  {
    department: "Product Management",
    company: "Voonix",
    gender: "Male",
    language: "Italian",
    first_name: "Laurie",
    ssn: "502-06-8131",
  },
  {
    department: "Services",
    company: "InnoZ",
    gender: "Female",
    language: "Oriya",
    first_name: "Elmira",
    ssn: "472-73-6646",
  },
  {
    department: "Marketing",
    company: "Tagtune",
    gender: "Male",
    language: "Azeri",
    first_name: "Newton",
    ssn: "616-49-1962",
  },
  {
    department: "Engineering",
    company: "Izio",
    gender: "Female",
    language: "Albanian",
    first_name: "Kissiah",
    ssn: "228-92-4521",
  },
  {
    department: "Support",
    company: "Ainyx",
    gender: "Male",
    language: "Portuguese",
    first_name: "Sherm",
    ssn: "457-15-0228",
  },
  {
    department: "Accounting",
    company: "Vimbo",
    gender: "Male",
    language: "French",
    first_name: "Johnny",
    ssn: "152-65-6717",
  },
  {
    department: "Research and Development",
    company: "Zoonoodle",
    gender: "Polygender",
    language: "Punjabi",
    first_name: "Ingamar",
    ssn: "127-74-0671",
  },
  {
    department: "Services",
    company: "Centidel",
    gender: "Female",
    language: "Tok Pisin",
    first_name: "Lisha",
    ssn: "736-58-0060",
  },
  {
    department: "Accounting",
    company: "Fiveclub",
    gender: "Female",
    language: "Gagauz",
    first_name: "Janaya",
    ssn: "568-64-3367",
  },
  {
    department: "Research and Development",
    company: "Tekfly",
    gender: "Female",
    language: "Telugu",
    first_name: "Christin",
    ssn: "164-97-2007",
  },
  {
    department: "Research and Development",
    company: "Rhynyx",
    gender: "Genderfluid",
    language: "Portuguese",
    first_name: "Gale",
    ssn: "275-57-3336",
  },
  {
    department: "Marketing",
    company: "Zoozzy",
    gender: "Female",
    language: "Fijian",
    first_name: "Fara",
    ssn: "334-18-5511",
  },
  {
    department: "Accounting",
    company: "Buzzbean",
    gender: "Female",
    language: "Kyrgyz",
    first_name: "Chicky",
    ssn: "667-56-5633",
  },
  {
    department: "Marketing",
    company: "Dabvine",
    gender: "Female",
    language: "Sotho",
    first_name: "Cecilla",
    ssn: "130-97-6582",
  },
  {
    department: "Human Resources",
    company: "Zava",
    gender: "Female",
    language: "Maltese",
    first_name: "Jilly",
    ssn: "698-52-7078",
  },
  {
    department: "Marketing",
    company: "Mita",
    gender: "Female",
    language: "Hebrew",
    first_name: "Luciana",
    ssn: "783-79-4649",
  },
  {
    department: "Training",
    company: "Snaptags",
    gender: "Male",
    language: "French",
    first_name: "Ruddie",
    ssn: "668-71-3403",
  },
  {
    department: "Sales",
    company: "Fadeo",
    gender: "Male",
    language: "Dari",
    first_name: "Oswell",
    ssn: "289-67-9593",
  },
  {
    department: "Human Resources",
    company: "Brightbean",
    gender: "Female",
    language: "Persian",
    first_name: "Ina",
    ssn: "288-88-7661",
  },
  {
    department: "Training",
    company: "Topicshots",
    gender: "Male",
    language: "Somali",
    first_name: "Randell",
    ssn: "823-76-7262",
  },
  {
    department: "Support",
    company: "Lazzy",
    gender: "Agender",
    language: "Marathi",
    first_name: "Sammie",
    ssn: "362-12-7461",
  },
  {
    department: "Sales",
    company: "Thoughtworks",
    gender: "Female",
    language: "Papiamento",
    first_name: "Emelina",
    ssn: "139-90-7653",
  },
  {
    department: "Product Management",
    company: "Dynava",
    gender: "Female",
    language: "Hebrew",
    first_name: "Emmaline",
    ssn: "306-19-4292",
  },
  {
    department: "Human Resources",
    company: "Ooba",
    gender: "Bigender",
    language: "Tok Pisin",
    first_name: "Kalil",
    ssn: "161-59-0416",
  },
  {
    department: "Human Resources",
    company: "Mynte",
    gender: "Male",
    language: "Chinese",
    first_name: "Albert",
    ssn: "129-01-7469",
  },
  {
    department: "Engineering",
    company: "Tagpad",
    gender: "Male",
    language: "Quechua",
    first_name: "Neddy",
    ssn: "549-56-8003",
  },
  {
    department: "Product Management",
    company: "Twinder",
    gender: "Male",
    language: "Northern Sotho",
    first_name: "Farr",
    ssn: "338-34-2768",
  },
  {
    department: "Research and Development",
    company: "Centimia",
    gender: "Female",
    language: "Zulu",
    first_name: "Lina",
    ssn: "848-86-2549",
  },
  {
    department: "Legal",
    company: "Vitz",
    gender: "Female",
    language: "Telugu",
    first_name: "Ruthy",
    ssn: "750-23-3933",
  },
  {
    department: "Legal",
    company: "Quamba",
    gender: "Female",
    language: "Filipino",
    first_name: "Mable",
    ssn: "370-43-2101",
  },
  {
    department: "Legal",
    company: "Livefish",
    gender: "Bigender",
    language: "Malayalam",
    first_name: "Cinnamon",
    ssn: "763-23-0030",
  },
  {
    department: "Sales",
    company: "Myworks",
    gender: "Male",
    language: "Chinese",
    first_name: "Lalo",
    ssn: "772-78-0400",
  },
  {
    department: "Marketing",
    company: "Voonte",
    gender: "Male",
    language: "German",
    first_name: "Griffin",
    ssn: "381-68-1163",
  },
  {
    department: "Training",
    company: "Gigabox",
    gender: "Male",
    language: "Kashmiri",
    first_name: "Pennie",
    ssn: "524-92-5011",
  },
  {
    department: "Legal",
    company: "Fiveclub",
    gender: "Genderfluid",
    language: "Chinese",
    first_name: "Helaine",
    ssn: "586-71-9533",
  },
  {
    department: "Legal",
    company: "Gabspot",
    gender: "Female",
    language: "Czech",
    first_name: "Denice",
    ssn: "664-56-0710",
  },
  {
    department: "Accounting",
    company: "Innojam",
    gender: "Female",
    language: "Greek",
    first_name: "Zelma",
    ssn: "325-97-1245",
  },
  {
    department: "Product Management",
    company: "Kaymbo",
    gender: "Male",
    language: "Bengali",
    first_name: "Deane",
    ssn: "611-97-6503",
  },
  {
    department: "Research and Development",
    company: "Skilith",
    gender: "Male",
    language: "Oriya",
    first_name: "Toiboid",
    ssn: "654-53-9222",
  },
  {
    department: "Research and Development",
    company: "Topicblab",
    gender: "Female",
    language: "Amharic",
    first_name: "Birdie",
    ssn: "894-98-1940",
  },
  {
    department: "Training",
    company: "Edgetag",
    gender: "Male",
    language: "Ndebele",
    first_name: "Reggy",
    ssn: "376-61-1977",
  },
  {
    department: "Sales",
    company: "Livetube",
    gender: "Male",
    language: "Irish Gaelic",
    first_name: "Neils",
    ssn: "769-77-0299",
  },
  {
    department: "Marketing",
    company: "Jabbersphere",
    gender: "Female",
    language: "Gujarati",
    first_name: "Zondra",
    ssn: "417-06-1301",
  },
  {
    department: "Research and Development",
    company: "Podcat",
    gender: "Female",
    language: "Luxembourgish",
    first_name: "Bessy",
    ssn: "297-12-4515",
  },
  {
    department: "Training",
    company: "Bluejam",
    gender: "Female",
    language: "Arabic",
    first_name: "Angy",
    ssn: "250-97-3012",
  },
  {
    department: "Business Development",
    company: "Jaxspan",
    gender: "Female",
    language: "Assamese",
    first_name: "Gilbertina",
    ssn: "239-09-3968",
  },
  {
    department: "Support",
    company: "Zoonoodle",
    gender: "Female",
    language: "Lithuanian",
    first_name: "Consuela",
    ssn: "888-68-1089",
  },
  {
    department: "Sales",
    company: "Eayo",
    gender: "Male",
    language: "Tamil",
    first_name: "Tomaso",
    ssn: "829-43-4252",
  },
  {
    department: "Support",
    company: "Skidoo",
    gender: "Male",
    language: "English",
    first_name: "Prince",
    ssn: "105-03-1411",
  },
  {
    department: "Engineering",
    company: "Jamia",
    gender: "Female",
    language: "Bislama",
    first_name: "Hedy",
    ssn: "872-85-7381",
  },
  {
    department: "Product Management",
    company: "Mybuzz",
    gender: "Female",
    language: "Chinese",
    first_name: "Jesselyn",
    ssn: "789-12-4380",
  },
  {
    department: "Human Resources",
    company: "Rhyloo",
    gender: "Male",
    language: "Hiri Motu",
    first_name: "Price",
    ssn: "516-89-1711",
  },
  {
    department: "Business Development",
    company: "Minyx",
    gender: "Male",
    language: "Japanese",
    first_name: "Georgie",
    ssn: "465-65-4778",
  },
  {
    department: "Services",
    company: "Katz",
    gender: "Female",
    language: "Japanese",
    first_name: "Domeniga",
    ssn: "857-77-1689",
  },
  {
    department: "Services",
    company: "Plambee",
    gender: "Genderfluid",
    language: "Chinese",
    first_name: "Ida",
    ssn: "829-24-7532",
  },
  {
    department: "Business Development",
    company: "Realmix",
    gender: "Male",
    language: "Ndebele",
    first_name: "Arie",
    ssn: "734-77-3476",
  },
  {
    department: "Services",
    company: "Yambee",
    gender: "Male",
    language: "Assamese",
    first_name: "Brig",
    ssn: "825-50-9338",
  },
  {
    department: "Marketing",
    company: "Skynoodle",
    gender: "Female",
    language: "Pashto",
    first_name: "Jana",
    ssn: "413-89-4446",
  },
  {
    department: "Product Management",
    company: "Skippad",
    gender: "Male",
    language: "German",
    first_name: "Alick",
    ssn: "104-26-2118",
  },
  {
    department: "Sales",
    company: "Mudo",
    gender: "Male",
    language: "Amharic",
    first_name: "Georas",
    ssn: "839-88-7877",
  },
  {
    department: "Engineering",
    company: "Blogspan",
    gender: "Male",
    language: "Khmer",
    first_name: "Clay",
    ssn: "376-48-3301",
  },
  {
    department: "Services",
    company: "Skiba",
    gender: "Female",
    language: "Zulu",
    first_name: "Shanta",
    ssn: "499-56-5002",
  },
  {
    department: "Sales",
    company: "Twitterbeat",
    gender: "Female",
    language: "Tswana",
    first_name: "Rakel",
    ssn: "767-81-3378",
  },
  {
    department: "Product Management",
    company: "Roombo",
    gender: "Male",
    language: "Czech",
    first_name: "Onfre",
    ssn: "765-88-2355",
  },
  {
    department: "Human Resources",
    company: "Thoughtbridge",
    gender: "Bigender",
    language: "Bosnian",
    first_name: "Cirilo",
    ssn: "616-94-4274",
  },
  {
    department: "Human Resources",
    company: "Brainsphere",
    gender: "Female",
    language: "Japanese",
    first_name: "Leonora",
    ssn: "238-65-0690",
  },
  {
    department: "Training",
    company: "Fivespan",
    gender: "Female",
    language: "Pashto",
    first_name: "Giulietta",
    ssn: "330-53-6248",
  },
  {
    department: "Engineering",
    company: "Ooba",
    gender: "Female",
    language: "Kannada",
    first_name: "Milli",
    ssn: "780-37-6870",
  },
  {
    department: "Accounting",
    company: "Podcat",
    gender: "Male",
    language: "Guaraní",
    first_name: "Hector",
    ssn: "733-48-6507",
  },
  {
    department: "Research and Development",
    company: "Fanoodle",
    gender: "Male",
    language: "Kannada",
    first_name: "Jeffie",
    ssn: "129-45-4269",
  },
  {
    department: "Human Resources",
    company: "Thoughtbridge",
    gender: "Female",
    language: "Tajik",
    first_name: "Garland",
    ssn: "894-21-5261",
  },
  {
    department: "Business Development",
    company: "Buzzshare",
    gender: "Male",
    language: "Khmer",
    first_name: "Purcell",
    ssn: "476-63-1706",
  },
  {
    department: "Business Development",
    company: "Mudo",
    gender: "Male",
    language: "Pashto",
    first_name: "Terry",
    ssn: "117-35-7286",
  },
  {
    department: "Legal",
    company: "Brainlounge",
    gender: "Male",
    language: "French",
    first_name: "Gustavo",
    ssn: "869-11-9097",
  },
  {
    department: "Accounting",
    company: "Geba",
    gender: "Male",
    language: "Chinese",
    first_name: "Frederigo",
    ssn: "198-23-2901",
  },
  {
    department: "Marketing",
    company: "Vitz",
    gender: "Male",
    language: "Yiddish",
    first_name: "Tucky",
    ssn: "273-54-6078",
  },
  {
    department: "Services",
    company: "Zooxo",
    gender: "Agender",
    language: "Ndebele",
    first_name: "Tim",
    ssn: "340-57-4020",
  },
  {
    department: "Accounting",
    company: "Jatri",
    gender: "Male",
    language: "Papiamento",
    first_name: "Mandel",
    ssn: "278-06-5563",
  },
  {
    department: "Engineering",
    company: "Quamba",
    gender: "Male",
    language: "Latvian",
    first_name: "Noach",
    ssn: "620-95-9621",
  },
  {
    department: "Services",
    company: "Livetube",
    gender: "Female",
    language: "Assamese",
    first_name: "Clara",
    ssn: "873-74-6686",
  },
  {
    department: "Support",
    company: "Browsebug",
    gender: "Female",
    language: "Hungarian",
    first_name: "Albina",
    ssn: "892-93-3360",
  },
  {
    department: "Support",
    company: "Jabbersphere",
    gender: "Male",
    language: "Tok Pisin",
    first_name: "Killian",
    ssn: "619-01-7151",
  },
  {
    department: "Marketing",
    company: "Buzzdog",
    gender: "Male",
    language: "Gagauz",
    first_name: "Shell",
    ssn: "485-22-2124",
  },
  {
    department: "Business Development",
    company: "Mymm",
    gender: "Male",
    language: "Mongolian",
    first_name: "Zachery",
    ssn: "266-15-7550",
  },
  {
    department: "Sales",
    company: "Chatterbridge",
    gender: "Male",
    language: "Nepali",
    first_name: "Calvin",
    ssn: "344-99-2405",
  },
  {
    department: "Sales",
    company: "Wikido",
    gender: "Male",
    language: "Malay",
    first_name: "Jourdain",
    ssn: "400-45-8881",
  },
  {
    department: "Legal",
    company: "Jetpulse",
    gender: "Male",
    language: "Macedonian",
    first_name: "Franny",
    ssn: "880-35-6090",
  },
  {
    department: "Services",
    company: "Skipfire",
    gender: "Female",
    language: "Burmese",
    first_name: "Avril",
    ssn: "687-75-7864",
  },
  {
    department: "Legal",
    company: "Babbleset",
    gender: "Female",
    language: "French",
    first_name: "Kaitlyn",
    ssn: "543-74-2271",
  },
  {
    department: "Marketing",
    company: "Quimba",
    gender: "Male",
    language: "Kashmiri",
    first_name: "Waldo",
    ssn: "571-37-8966",
  },
  {
    department: "Services",
    company: "Npath",
    gender: "Female",
    language: "Irish Gaelic",
    first_name: "Robinett",
    ssn: "734-13-3587",
  },
  {
    department: "Sales",
    company: "Photofeed",
    gender: "Female",
    language: "Catalan",
    first_name: "Theodora",
    ssn: "537-51-4281",
  },
  {
    department: "Accounting",
    company: "Zoovu",
    gender: "Male",
    language: "Filipino",
    first_name: "Davie",
    ssn: "653-22-4067",
  },
  {
    department: "Training",
    company: "Omba",
    gender: "Male",
    language: "Japanese",
    first_name: "Donny",
    ssn: "353-57-1322",
  },
  {
    department: "Business Development",
    company: "Wordpedia",
    gender: "Female",
    language: "Macedonian",
    first_name: "Fred",
    ssn: "485-77-5955",
  },
  {
    department: "Product Management",
    company: "Quatz",
    gender: "Female",
    language: "Fijian",
    first_name: "Saraann",
    ssn: "593-62-4824",
  },
  {
    department: "Accounting",
    company: "Yodo",
    gender: "Male",
    language: "Chinese",
    first_name: "Galvin",
    ssn: "768-86-4375",
  },
  {
    department: "Legal",
    company: "Tekfly",
    gender: "Female",
    language: "Dzongkha",
    first_name: "Mia",
    ssn: "489-96-1309",
  },
  {
    department: "Business Development",
    company: "Quamba",
    gender: "Polygender",
    language: "Tswana",
    first_name: "Zed",
    ssn: "387-92-1569",
  },
  {
    department: "Support",
    company: "Skiptube",
    gender: "Male",
    language: "Hiri Motu",
    first_name: "Graehme",
    ssn: "550-88-1560",
  },
  {
    department: "Sales",
    company: "Yakijo",
    gender: "Male",
    language: "Czech",
    first_name: "Cheston",
    ssn: "525-90-6806",
  },
  {
    department: "Marketing",
    company: "Zoombeat",
    gender: "Male",
    language: "Bengali",
    first_name: "Abbot",
    ssn: "521-02-8057",
  },
  {
    department: "Business Development",
    company: "Shuffledrive",
    gender: "Bigender",
    language: "Tamil",
    first_name: "Eldon",
    ssn: "225-56-3365",
  },
  {
    department: "Human Resources",
    company: "Gabtune",
    gender: "Female",
    language: "Maltese",
    first_name: "Ingrid",
    ssn: "848-95-6295",
  },
  {
    department: "Accounting",
    company: "Avaveo",
    gender: "Female",
    language: "Zulu",
    first_name: "Julie",
    ssn: "780-19-7848",
  },
  {
    department: "Services",
    company: "Yoveo",
    gender: "Female",
    language: "Arabic",
    first_name: "Ninnetta",
    ssn: "172-69-1510",
  },
  {
    department: "Engineering",
    company: "Photofeed",
    gender: "Male",
    language: "Romanian",
    first_name: "Ignazio",
    ssn: "896-97-0089",
  },
  {
    department: "Human Resources",
    company: "Browsecat",
    gender: "Female",
    language: "Greek",
    first_name: "Daryn",
    ssn: "543-13-7226",
  },
  {
    department: "Human Resources",
    company: "Skilith",
    gender: "Male",
    language: "Bislama",
    first_name: "Angel",
    ssn: "534-92-9650",
  },
  {
    department: "Research and Development",
    company: "Wordware",
    gender: "Male",
    language: "Montenegrin",
    first_name: "Ossie",
    ssn: "449-89-9646",
  },
  {
    department: "Support",
    company: "Ainyx",
    gender: "Male",
    language: "Azeri",
    first_name: "Chen",
    ssn: "693-88-1268",
  },
  {
    department: "Research and Development",
    company: "Tagpad",
    gender: "Male",
    language: "Korean",
    first_name: "Cly",
    ssn: "573-05-2058",
  },
  {
    department: "Accounting",
    company: "Lajo",
    gender: "Female",
    language: "Tswana",
    first_name: "Beverlie",
    ssn: "238-59-5216",
  },
  {
    department: "Research and Development",
    company: "Edgewire",
    gender: "Male",
    language: "Italian",
    first_name: "Jdavie",
    ssn: "481-88-3156",
  },
  {
    department: "Sales",
    company: "Twitterlist",
    gender: "Female",
    language: "Luxembourgish",
    first_name: "Shaylyn",
    ssn: "571-71-8461",
  },
  {
    department: "Business Development",
    company: "Skimia",
    gender: "Female",
    language: "Somali",
    first_name: "Carolan",
    ssn: "887-19-0718",
  },
  {
    department: "Research and Development",
    company: "Brightbean",
    gender: "Male",
    language: "Croatian",
    first_name: "Desmond",
    ssn: "185-89-9460",
  },
  {
    department: "Research and Development",
    company: "Rhycero",
    gender: "Female",
    language: "Polish",
    first_name: "Binni",
    ssn: "114-55-0705",
  },
  {
    department: "Legal",
    company: "Dabfeed",
    gender: "Female",
    language: "Hindi",
    first_name: "Cherry",
    ssn: "586-37-4974",
  },
  {
    department: "Accounting",
    company: "Realfire",
    gender: "Male",
    language: "Portuguese",
    first_name: "Jarred",
    ssn: "535-68-5140",
  },
  {
    department: "Research and Development",
    company: "Ailane",
    gender: "Male",
    language: "Albanian",
    first_name: "Keen",
    ssn: "541-85-0495",
  },
  {
    department: "Legal",
    company: "Yodo",
    gender: "Female",
    language: "Catalan",
    first_name: "Harrietta",
    ssn: "829-28-5148",
  },
];

// const engineering = data.filter((x) => x.department == "Engineering");
// console.log(engineering);

// const japaneseMale = data
//   .filter((x) => x.gender == "Male" && x.language == "Japanese")
//   .map((x) => {
//     return { department: x.department, first_name: x.first_name };
//   });
// console.log(japaneseMale);

// const evenAndName = data.filter(
//   (x) =>
//     // !(Number(x.ssn.split("-")[2]) % 2) &&
//     !(Number(x.ssn[x.ssn.length - 1]) % 2) &&
//     ["K", "B", "S"].some((y) => x.first_name.startsWith(y))
// );
// console.log(evenAndName);

const newData = data
  .filter(
    (x) =>
      x.language === "Korean" ||
      x.language === "Japanese" ||
      x.language === "Chainese"
  )
  .filter((x) => x.gender === "Female")
  .filter((x) => {
    // const first = [x.ssn.split("-")[0]];
    // return Number(first[0]) + Number(first[1]) + Number(first[2]) > 10;
    return (
      Number([...x.ssn][0]) + Number([...x.ssn][1]) + Number([...x.ssn][2]) > 10
    );
  });
console.log(newData);
